=== dustin-crossman/mbed-os/tools/config/schema_lib.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "title": "Mbed Library Schema",
  "description": "Configuration file for an mbed library",
  "type": "object",
  "$id": "http://example.com/root.json",
  "properties": {
    "name": {
      "$ref": "file:definitions.json#/name_definition"
    },
    "config": {
      "$ref": "file:definitions.json#/config_definition"
    },
    "target_overrides": {
      "$ref": "file:definitions.json#/target_overrides_definition"
    },
    "macros": {
      "$ref": "file:definitions.json#/macro_definition"
    }
  },
  "required": [
    "name"
  ],
  "additionalProperties": false
}

=== dustin-crossman/mbed-os/rtos/mbed_lib.json
{
    "name": "rtos",
    "config": {
        "present": 1
    },
    "macros": ["_RTE_"],
    "target_overrides": {
        "*": {
            "target.boot-stack-size": "0x400"
        },
	    "MCU_NRF51": {
	        "target.boot-stack-size": "0x800"
	    },
	    "MCU_NRF52840": {
	        "target.boot-stack-size": "0x800"
	    },
	    "MCU_NRF52832": {
	        "target.boot-stack-size": "0x800"
	    },
	    "MCU_NRF51_UNIFIED": {
	        "target.boot-stack-size": "0x800"
	    }
    }
}
